apiVersion: v1
kind: Service
metadata:
  name: untitled-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0d7d79761840ef5be"
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-04b4cb7f432985641"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:sa-east-1:324555808373:certificate/5038ba01-2035-4098-a0ee-8cd6e19b346c
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    service.beta.kubernetes.io/aws-load-balancer-security-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
spec:
  selector:
    app: untitled-front
  ports:
    - protocol: TCP
      name: https
      port: 443
      targetPort: 4200
    - protocol: TCP
      name: http
      port: 80
      targetPort: 4200
  type: LoadBalancer
